name: Pull Request CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'mandrel-latest'
        java-version: '17'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Maven build
      run: mvn -B install -Pnative
    - name: Sonar
      env:
        SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      run: |
        mvn org.jacoco:jacoco-maven-plugin:prepare-agent org.apache.maven.plugins:maven-surefire-plugin:test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.login=$SONARCLOUD_TOKEN